In [96]:
b =np.array([[500,400,3.14],[100,200,np.pi/10],[100,200,3.14]])
b

array([[5.00000000e+02, 4.00000000e+02, 3.14000000e+00],
       [1.00000000e+02, 2.00000000e+02, 3.14159265e-01],
       [1.00000000e+02, 2.00000000e+02, 3.14000000e+00]])

In [97]:
b=np.float32(b)
b[:,2] = b[:,2]/np.pi
# b[:,:2] = b[:,:2]/500
# b.reshape(-1)
b

array([[5.0000000e+02, 4.0000000e+02, 9.9949306e-01],
       [1.0000000e+02, 2.0000000e+02, 1.0000000e-01],
       [1.0000000e+02, 2.0000000e+02, 9.9949306e-01]], dtype=float32)

In [93]:
a=1

In [73]:
a *= 35
a += 35
a

70

In [98]:
b =np.array([500,400,3.14])
b

array([500.  , 400.  ,   3.14])

In [99]:
b=np.float32(b)
b[2] = b[2]/np.pi
b[:2] = b[:2]/500
b.reshape(-1)
b

array([1.        , 0.8       , 0.99949306], dtype=float32)

In [1]:
def  aaa():
    print('1')

In [4]:
eee = aaa

In [5]:
eee()

1
